site_name: "Programming Languages: Application and Interpretation"
repo_url: https://github.com/lotuc/PLAI-cn.git
docs_dir: docs

theme:
  name: material

plugins: []

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-CRZZK8N4WE

