site_name: "Programming Languages: Application and Interpretation"
repo_url: https://github.com/ck76/PLAI-cn
docs_dir: docs

theme:
  name: material

plugins:
  - with-pdf:
      #cover_title:
      cover_subtitle: Technical documentation that just works
      cover_logo: assets/images/banner.png
      back_cover: true
      toc_level: 2
      excludes_children:
        - 'releases/changelog/:upgrading'
      convert_iframe:
        - src: https://streamable.com/e/zmtb00
          img: https://cdn-cf-east.streamable.com/image/zmtb00-screenshot75403.jpg
      two_columns_level: 3
      render_js: true
      #headless_chrome_path: google-chrome
      output_path: ../document.pdf
      #debug_html: true
      #verbose: true
      #show_anchors: true
      #enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-CRZZK8N4WE

